# Generated by Django 4.2.2 on 2023-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skateparks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('lights', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('openinghours', models.CharField(max_length=500)),
                ('helmets', models.BooleanField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('surface', models.CharField(choices=[('CONCRETE', 'Concrete'), ('WOOD', 'Wood'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('indooroutdoor', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('fee', models.CharField(max_length=100)),
                ('pros', models.CharField(blank=True, max_length=500)),
                ('cons', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
