# Generated by Django 4.2.2 on 2023-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='helmets',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10),
        ),
    ]
