# Generated by Django 4.2.6 on 2023-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0003_alter_skateparks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
