# Generated by Django 4.2.6 on 2023-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0007_alter_skateparks_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='indooroutdoor',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('Un', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skateparks',
            name='surface',
            field=models.CharField(choices=[('CONCRETE', 'Concrete'), ('WOOD', 'Wood'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
    ]
