# Generated by Django 4.2.6 on 2024-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0008_alter_skateparks_indooroutdoor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='cons',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='skateparks',
            name='pros',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
