# Generated by Django 4.2.6 on 2024-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0009_alter_skateparks_cons_alter_skateparks_pros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
