# Generated by Django 4.2.6 on 2024-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0010_alter_skateparks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateparks',
            name='indooroutdoor',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skateparks',
            name='surface',
            field=models.CharField(choices=[('concrete', 'Concrete'), ('wood', 'Wood'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
